### ISSUE TITLE
KDE Plasma support

### ISSUE THREAD

**Issue by tjkirch** [rafaelrc7/wayland-pipewire-idle-inhibit#1]
Thanks for this program!  I'd love to use it, but I'm trying it [edit: 0.4.5 from nixpkgs on NixOS] with KDE Plasma 6.0.1, and unfortunately it doesn't work.  It correctly detects Pipewire audio and says it's setting idle inhibit, and there are no errors (even at TRACE level), but the screen blank / lock still happens.

~I see that the [wayland protocols crate was split](https://github.com/Smithay/wayland-rs/pull/478/files), introducing Plasma-specific Wayland protocols, including [KWin-specific idle inhibit](https://docs.rs/wayland-protocols-plasma/0.2.0/wayland_protocols_plasma/idle/client/index.html), whereas this create uses [zwp](https://docs.rs/wayland-protocols/0.31.0/wayland_protocols/wp/idle_inhibit/zv1/client/index.html).  That seems unfortunate, but~

I also found that a "standard" D-Bus call to [org.freedesktop.ScreenSaver](https://specifications.freedesktop.org/idle-inhibit-spec/latest/re01.html)'s method `Inhibit` works correctly, and is not KDE-specific.  You give it an application name and reason, and it returns an integer that you later give to `UnInhibit`.

Do you think it would make sense for this program to _also_ send D-Bus messages, or use the Plasma-specific API, to help KDE users?

**Comment by rafaelrc7** [comment]
Hello, thanks for the report! In theory, the program was supposed to work in Plasma, as since [5.12.0](https://kde.org/announcements/plasma/5/5.12.0/) it should support the `idle_inhibit_unstable_v1` protocol, so this looks like a bug.

The crate you linked (https://docs.rs/wayland-protocols-plasma/0.2.0/wayland_protocols_plasma/idle/client/index.html) is not related to idle inhibiting, but actually is a callback for applications to react when the system has gone idle and when it is awoken, for example for Discord to set your status as idle when your PC idles. So it is an unrelated protocol and this split is not a problem for this software and, as mentioned before, Plasma *should* support `idle_inhibit_unstable_v1`.

As my program works fine in Sway, it might point to this being a bug with Plasma? I will try to investigate it in the coming days, and if you find out anything else, please share.

About the D-Bus messages, it does seem to be a possible feature. If this is indeed a Plasma issue, it would be a fix, at least until the protocol works properly again. But anyway, it could be a nice feature to have, for better compatibility.

**Comment by rafaelrc7** [comment]
With the help of a friend, we tested the waybar idle inhibit button (that uses the same protocol) in Plasma, and it indeed work. So this confirms that this is a bug in my software, not Plasma. I will try to debug it in the next days.

**Comment by rafaelrc7** [comment]
Sorry, scratch that, waybar actually seems to use dbus, and thats why it worked on Plasma. We tried https://github.com/ErikReider/SwayAudioIdleInhibit, that was the original inspiration of this project, and it also did not work, so it seems to be indeed a Plasma issue.
