### ISSUE TITLE
Using home manager module without rebuilding package

### ISSUE THREAD

**Issue by tjkirch** [rafaelrc7/wayland-pipewire-idle-inhibit#8]
I like the home manager module because it gives automatic service management.  However, using this flake causes my system updates to frequently include all of the Rust dependencies, and for wayland-pipewire-idle-inhibit to have to be built locally.  Is there any way to get that benefit of the module without needing all of its dependencies in my system closure and without needing local builds?  (This is the only reason I use home manager.)

I'm still new to NixOS and haven't done a lot of custom work, but these ideas came to mind:
1) Is there a way to set something like `services.wayland-pipewire-idle-inhibit.package = nixpkgs.wayland-pipewire-idle-inhibit` so it uses the existing, pre-built package from nixpkgs, but the service from the flake?
2) Is there a way to get the service management baked into the nixpkgs version?
3) Or would it be easiest to abandon the module's service and define a user-level systemd service in my NixOS config?  I don't know how to tie it to package updates.

**Comment by rafaelrc7** [comment]
Hello, answering your questions:

1. Yes, you can do that. One of the options of the `wayland-pipewire-idle-inhibit` home-manager module is to set the package. You can do it by setting `services.wayland-pipewire-idle-inhibit.package = pkgs.wayland-pipewire-idle-inhibit`. This way, the module will use the package from nixpkgs instead of building it from scratch.
2. No, it would not be possible to bake the service into nixpkgs in a configurable manner. What it is possible to do, though, is to add the module to home-manager itself. This would make it unnecessary to include this projects flake, only home-manager, the configuration would possibly be the exact same and by default it would use nixpkgs package instead of the flake one.
3. It would make no difference, all you need to do is to point the module to use your nixpkgs instance's package. The home-manager module is just an abstraction over setting a systemd service, and it would be basically equivalent.

Does that help you with your doubts?

**Comment by tjkirch** [comment]
That's really helpful, thank you! I'll try out (1) and perhaps suggest a change to the README in case others are interested.
